
import type { Metadata } from "next";
import Highlight from '@/components/Highlight'

export const metadata: Metadata = {
  title: "About | Omelora",
  description: "Generated by create next app",
};

export default function AboutPage() {


    return (
        <section className="flex flex-col gap-20 justify-between">
            
        </section>
    )
}