
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function AboutPage() {

    return (
        <section className="flex flex-col gap-20 justify-between">
            <header className='flex flex-col gap-5'>
                <h1 className='ft-cooper'>Who We Are</h1>
                <p className='text-lg md:text-xl'>
                    Omelora, founded by Kyra, a high school student from Texas, is a social initiative aimed at providing resources and aid to vulnerable children in rural communities in southern Nigeria. Our goal is to drive environmental, health-focused, social, and educational change through various charitable activities.
                    <br/><br/>Through sharing stories, sharing resources, and sharing information, we aim to raise awareness about the critical environmental and health challenges facing our target areas. By highlighting these issues, we hope to empower individuals and communities to take action for positive change.
                    <br/><br/>Currently, our main initiative involves raising funds for the Divine Wounds of Jesus Christ Orphanage Home in Enugu, Nigeria. We&apos;re partnering with local businesses and sponsors to mobilize resources and support for the children in this orphanage, ensuring they have access to essential care and opportunities.
                </p>
            </header>
        </section>
    )
}