
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Omelora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <main className='p-5 md:px-[15vw] md:py-[10vh]'>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
