import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Partnerships | Omelora",
  description: "Generated by create next app",
};

export default function Partnerships() {
    return (
        <section className="flex flex-col gap-10">
            <header className='flex flex-col gap-5'>
                <h1 className='ft-cooper'>Partnerships</h1>
                <p className='text-base md:text-lg'>
                Through sharing stories, sharing resources, and sharing information, we aim to 
                raise awareness about the critical environmental and health challenges facing our 
                target areas. By highlighting these issues, we hope to empower individuals and 
                communities to take action for positive change.
                </p>
                <p>
                    For partnership inquiries, contact us at <b>omelorachildren@gmail.com</b>.
                </p>
            </header>
        </section>
    )
}