import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Partnerships | Omelora",
  description: "Generated by create next app",
};

export default function Partnerships() {
    return (
        <section className="flex flex-col gap-10">
            
        </section>
    )
}