import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Partnerships | Omelora",
  description: "Generated by create next app",
};

export default function Partnerships() {
    return (
        <section className="flex flex-col gap-10">
            <header className='flex flex-col gap-5'>
                <h1 className='ft-cooper'>Partnerships</h1>
                <p className='text-base md:text-lg'>
                We are establishing strong partnerships with local businesses to support 
                our mission, enhancing our impact and reach. Additionally, we welcome 
                media inquiries and collaboration opportunities. For more information 
                or to get involved, please contact us.
                </p>
                <p>
                For partnership inquiries, contact us at <b>omelorachildren@gmail.com</b>.
                </p>
            </header>
        </section>
    )
}