
import type { Metadata } from "next";
import Highlight from '@/components/Highlight'
export const metadata: Metadata = {
  title: "About Us | Omelora",
  description: "Generated by create next app",
};

export default function AboutPage() {

    const OmeloraHighlight = 
    <Highlight toggleElement={<span className='font-semibold'>Omelora</span>}>
        <div className='flex flex-col gap-1 font-medium'>
        Omelora is an Igbo Nigerian word that means &quot;One who does good for the community.&quot;
        </div>
    </Highlight>

    const DwaHighlight = 
    <Highlight toggleElement={<span className='font-semibold ' >Divine</span>}>
        <div className='flex flex-col gap-1 font-medium'>
        All kits contain basic school supplies including 1 notebook, colored pencils, a book, custom STEM pamphlet, and a pencil pouch.
        </div>
    </Highlight>

    return (
        <section className="flex flex-col gap-20 justify-between">
            <header className='flex flex-col gap-5'>
                <h1 className='ft-cooper'>About Us</h1>
                <p className='text-lg md:text-xl'>
                    {OmeloraHighlight}, founded by Kyra, a high school student from Texas, is a social initiative aimed at providing resources and aid to vulnerable children in rural communities in southern Nigeria. Our goal is to drive environmental, health-focused, social, and educational change through various charitable activities.
                    <br/><br/>Through sharing stories, sharing resources, and sharing information, we aim to raise awareness about the critical environmental and health challenges facing our target areas. By highlighting these issues, we hope to empower individuals and communities to take action for positive change.
                    <br/><br/>Currently, our main initiative involves raising funds for the {DwaHighlight} <span className='txt-underline-base'>Wounds of Jesus Christ Orphanage Home</span>. We&apos;re partnering with local businesses and sponsors to mobilize resources and support for the children in this orphanage, ensuring they have access to essential care and opportunities.
                </p>
            </header>
        </section>
    )
}