import {initiatives, dwaSiteLink} from '@/data/content'
import Campaign from '@/components/Campaign'
import Highlight from '@/components/Highlight'

import Link from 'next/link'

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Our Initiatives | Omelora",
  description: "Generated by create next app",
};

export default function OurInitiativesPage() {

    const DwaHighlight = 
    <Highlight toggleElement={<span className='font-semibold ' >Divine</span>}>
      <div className='flex flex-col gap-1 font-medium'>
        All kits contain basic school supplies including 1 notebook, colored pencils, a book, custom STEM pamphlet, and a pencil pouch.
      </div>
    </Highlight>

    return (
        <section className="flex flex-col gap-10">
            <header className='flex flex-col gap-5'>
                <h1 className='ft-cooper'>Our Initiatives</h1>
                <p className='text-base md:text-lg'>
                  Our current focus is the children of 
                  the {DwaHighlight} <span className='txt-underline-base'>Wounds of Jesus Christ Orphanage Home</span> in Enugu, Nigeria.
                  We&apos;re extending educational support through charitable endeavors.
                </p>
                <p className='text-base md:text-lg'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas risus orci, hendrerit vitae placerat at, tincidunt id risus. Nulla id risus eleifend, bibendum nisi in, feugiat lorem. Ut dignissim lacinia dolor eget tempor. Integer vitae pretium mi. Sed faucibus felis nec quam efficitur egestas ut in tellus. 
                </p>
            </header>

            <div className='flex flex-col lg:grid grid-cols-3 gap-5'>
              {initiatives.map((item,index)=>(
                <Campaign
                key={index}
                title={item.title}
                location={item.location}
                description={item.description}
                goalValue={item.goalValue}
                currentValue={item.currentValue}
                startDate={item.startDate}
                endDate={item.endDate}
                measurement={item.measurement}
                orgsSupporting={item.orgsSupporting}
                image={item.image}
                />
              ))}
            </div>
        </section>
    )
}