import {initiatives, dwaSiteLink} from '@/data/content'
import Campaign from '@/components/Campaign'
import Highlight from '@/components/Highlight'

import Link from 'next/link'

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Our Initiatives | Omelora",
  description: "Generated by create next app",
};

export default function OurInitiativesPage() {

    return (
        <section className="flex flex-col gap-10">
            <header className='flex flex-col gap-5'>
                <h1 className='ft-cooper'>Our Initiatives</h1>
                <p className='text-base md:text-lg'>
                  Our current focus is the children of the 
                  Divine Wounds of Jesus Christ Orphanage Home in Enugu, Nigeria.
                  We&apos;re extending educational support through charitable endeavors.
                </p>
                <p className='text-base md:text-lg'>
                  In Houston, we&apos;re collaborating with local businesses to gather 
                  essential school supplies for the Divine Wounds of Jesus Christ Orphanage Home 
                  in Enugu, Nigeria, ensuring these children have the tools they need to learn and grow. 
                  Through community efforts, we&apos;re making education accessible and impactful for those in need.
                </p>
            </header>

            <div className='flex flex-col lg:grid grid-cols-3 gap-5'>
              {initiatives.map((item,index)=>(
                <Campaign
                key={index}
                title={item.title}
                location={item.location}
                description={item.description}
                goalValue={item.goalValue}
                currentValue={item.currentValue}
                startDate={item.startDate}
                endDate={item.endDate}
                measurement={item.measurement}
                orgsSupporting={item.orgsSupporting}
                image={item.image}
                />
              ))}
            </div>
        </section>
    )
}