import Link from 'next/link'
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Support Our Cause",
  description: "Generated by create next app",
};

export default function SupportOurCausePage() {

    return (
        <section className="flex flex-col gap-20">
            <header className='flex flex-col gap-5'>
                <h1 className='cooper'>Support Our Cause</h1>
                <p className='text-xl'>
                    Omelora as a social good initiative is currently looking for fiscal sponsorship to establish a secure way to receive donations. <br/> <br/>
                    Those who would like to support our cause can follow our <Link href='https://www.instagram.com/omeloraorg/' className='font-semibold'>Instagram</Link> where we have partnered with the <Link className='font-semibold' href='https://www.instagram.com/htxclimatestrike/'>Houston Climate Strike</Link> to create explainers about the effects our local actions can have on international environmental and health-focused wellbeing.
                </p>
            </header>
        </section>
    )
}